[[ISSUERS]]
address = "rJzq9Xwg1ZNRmSk5uyPoHdLDffpctv26CX"
name = "EmoCreations.skin"

[[TOKENS]]
issuer = "rJzq9Xwg1ZNRmSk5uyPoHdLDffpctv26CX"
currency = "XEC"
name = "XEC"
desc = "EmoCreations.skin - XEC, our AI doesn’t just blend oils —
it studies the science of synergy to create intelligent, evidence-informed elixirs that honor your skin’s innate intelligence. ."
icon = "https://emocreations.skin/public/xec-logo.png"
image = "https://emocreations.skin/public/xec-logo.png"

[[TOKENS.URLS]]
url = "https://emocreations.skin"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/EmoCreationSkin"
type = "social"

[[TOKENS.URLS]]
url = "https://instagram.com/emocreations.skin"
type = "social"

[[TOKENS.URLS]]
url = "https://youtube.com/emocskin-xec"
type = "social"

[[TOKENS.URLS]]
url = "https://facebook.com/EmoCreations.skin"
type = "social"

[[TOKENS.URLS]]
url = "https://t.me/EmoCreationSkin"
type = "social"

[[TOKENS.URLS]]
url = "https://xpmarket.com/token/XEC-rJzq9Xwg1ZNRmSk5uyPoHdLDffpctv26CX"
type = "social"

[[PRINCIPALS]]
name = "Franz C. aka xecking"
email = "emoc.xec@gmail.com"

[[ACCOUNTS]]
address = "rJzq9Xwg1ZNRmSk5uyPoHdLDffpctv26CX"
address = "rssjeidoLy7dscFrYsY9FZc4Zh2ZxKeWee"



